### ISSUE TITLE
Fix test case for approximate tree search

### ISSUE THREAD

**Issue by kanodiaayush** [grf-labs/policytree#12]
" tree search with approximate splitting works as expected ": fix this test case as it fails sometimes.

**Comment by erikcs** [comment]
Can you say which test fails?

**Comment by kanodiaayush** [comment]
The test as cited above ("tree search with approximate splitting works as expected")..

**Comment by erikcs** [comment]
That [test](https://github.com/grf-labs/policytree/blob/master/tests/testthat/test_policy_tree.R#L270) has [8](https://github.com/grf-labs/policytree/blob/master/tests/testthat/test_policy_tree.R#L290) checks, are you saying all 8 checks always fail?

**Comment by kanodiaayush** [comment]
oh; within that. 

`expect_true(reward.skip2 > 1.5 * reward.colmax)`

This fails probabilistically. It passed with my current set of changes which are only aesthetically different from the last. Maybe we could hardcode the seed so that it does not fail probabilistically (at least on machines with Linux?).

 Does this show up as 8 tests or 1 test in the testing console (for my information)?

**Comment by erikcs** [comment]
It should show up as failed: "tree search with approximate splitting works as expected" then show which checks within that failed.

How about just changing it to `expect_true(reward.skip2 > reward.colmax)` which is just a loose check that it is not doing anything terrible (the behavior tested should be robust enough that it holds regardless of seed)

**Comment by kanodiaayush** [comment]
We can do that. I'll make this fix and push a PR.
Ayush Kanodia,

PhD Student,
Stanford Computer Science
