### ISSUE TITLE
What does Y.hat do in a causal forest

### ISSUE THREAD

**Issue by aczura2024** [grf-labs/policytree#174]
Hello,

I have been examining the causal_forest function for a while and am still unclear about what the Y.hat argument is exactly. I know that it is the estimated responses that are computed using a separate regression forest if NULL, but what exactly do these estimates correspond to in the context of a binary treatment assignment? Are they the estimates of the outcome for each subject that is not observed? If someone knows the answer or knows the appropriate literature to look at any help would be appreciated. 

Thanks in advance

**Comment by erikcs** [comment]
There's an overview and references here https://grf-labs.github.io/grf/articles/grf_guide.html.
