### ISSUE TITLE
Question: would double_robust_scores() and grf::instrumental_forest() work if one has continuous or multiple instruments

### ISSUE THREAD

**Issue by if-sudo** [grf-labs/policytree#75]
Would double_robust_scores() and grf::instrumental_forest() work if one has continuous or multiple instruments for policy learning?

**Comment by erikcs** [comment]
Hi @if-sudo, sorry, double_robust_scores is only implemented for binary instruments (fyi: https://github.com/grf-labs/grf/issues/756). And GRF's instrumental_forest does currently not support multiple instruments.

**Comment by if-sudo** [comment]
Thanks!
