### ISSUE TITLE
Constrained optimal policy

### ISSUE THREAD

**Issue by hhsievertsen** [grf-labs/policytree#93]
Hi team,

thanks again for developing these tools and being so responsive. Is there an easy way to find an optimal policy that is constrained to treating at most N individuals (i.e. I have a fixed budget)?

thanks,
Hans

**Comment by erikcs** [comment]
Hi @hhsievertsen, policytree only does unconstrained search at the moment.

You can however shift the objective function by the average cost of treatment C by subtracting it from the doubly robust scores, see section 5.1 in https://arxiv.org/pdf/1702.02896.pdf for an example (the replication code is [here](https://github.com/grf-labs/policytree/blob/master/experiments/athey_wager_2021/gain_analysis.R#L134).

(the supplemental material to https://onlinelibrary.wiley.com/doi/abs/10.3982/ECTA13288 has some MATLAB scripts that uses integer programming to find policies with constraints, they are not tree based however).

**Comment by hhsievertsen** [comment]
Hi @erikcs,
perfect. That works.
Thank you!
